# mkdocs.yml
site_name: Ash & Light
docs_dir: docs
site_dir: site

theme:
  name: material
  logo: images/logo.png
  features:
    - navigation.sections
    - navigation.expand
    - navigation.tracking

plugins:
  - search

markdown_extensions:
  - pymdownx.snippets:
      base_path: docs
  - attr_list

extra_css:
  - stylesheets/extra.css

nav:
  - Introduction:
      - Overview: "/#introduction"
      - Game Description: "/#introduction"
  - Playing a Character:
      - Overview: "/#playing-a-character"
      - Types: "/#playing-a-character"
      - Classes: "/#playing-a-character"
      - Alignment: "/#playing-a-character"
  - The World:
      - Overview: "/#the-world"
      - Mythology: "/#the-world"
      - Archons: "/#the-world"
      - Timeline: "/#the-world"
      - Prophecy: "/#the-world"
  - Systems:
      - Overview: "/#systems"
      - Party and Companions: "/#systems"
      - Combat: "/#systems"
      - Progression and Levels: "/#systems"
      - Exploration, Gear, Resources, Logistics: "/#systems"
      - Economy, Crafting, Upgrades: "/#systems"
