# mkdocs.yml
site_name: Ash & Light
docs_dir: docs
site_dir: site

theme:
  name: material
  logo: images/logo.png
  features:
    - navigation.sections
    - navigation.expand
    - navigation.tracking

plugins:
  - search

markdown_extensions:
  - pymdownx.snippets:
      base_path: docs

extra_css:
  - stylesheets/extra.css

nav:
  - Codex: index.md
